packages:
  - "api-server"
  - "typescript-sdk"
  - "integration-tests/typescript"
  - "integration-tests/cross-sdk"
allowBuilds:
  simple-git-hooks: true
  "@prisma/engines": true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - "@astrojs/internal-helpers@0.10.2"
  - "@astrojs/markdown-satteri@0.3.5"
  - astro@7.1.5
